---
version: 2

project_name: gocover-ui

upx:
  - enabled: true

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/tschaefer/cover-ui/internal/version.Version={{.Version}}
      - -X github.com/tschaefer/cover-ui/internal/version.GitCommit={{.FullCommit}}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"


changelog:
  disable: true
